--CREATE DATABASE `joke` /*!40100 COLLATE 'utf8_general_ci' */;
--CREATE USER 'joke'@'%' IDENTIFIED BY 'joke';
--GRANT USAGE ON *.* TO 'joke'@'%';
--GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `joke`.* TO 'joke'@'%' WITH GRANT OPTION;
--FLUSH PRIVILEGES;

CREATE TABLE `customer` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255) NULL DEFAULT NULL,
	`contact` VARCHAR(255) NULL DEFAULT NULL,
	`telephone` VARCHAR(255) NULL DEFAULT NULL,
	`email` VARCHAR(255) NULL DEFAULT NULL,
	`remark` TEXT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
